version: '3'
services:
  sheets:
    build: .
    depends_on:
    - database

  database:
    image: postgres:latest
    volumes: 
    - postg:/var/lib/postgresql/data/
    environment:
    - POSTGRES_PASSWORD=1234
    ports:
    - 5432:5432
volumes:
  postg:
